name: Library CI

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  playwright-tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Start Backend
        run: node server/server.js &

      - name: Start Frontend
        run: npm start &

      - name: Wait For App
        run: sleep 10

      - name: Run Tests
        run: npm test
